### ISSUE TITLE
Problems with cpu/ram parameters

### ISSUE THREAD

**Issue by senseicoder** [sysC0D/nagios-plugin#1]
Hi, 

[ec2-user@ip-172-31-44-152 ~]$ sudo bash check_docker.sh --name voo4-collecte --status --cpulimitperc=00,90
**Unknown argument: --cpulimitperc=00,90**
Usage: ./check_docker_stats.sh [-v] [-h] [-n [-s -c -m -N]]
        -h, --help
        print this help message
        -v, --version
        print version program
        -n, --name
        name docker to check
        -c, --cpulimitperc=PERC_WARNING_CPU,PERC_CRITCAL_CPU
        number in percent alert for CPU
        -m, --memlimitperc=PERC_WARNING_MEM,PERC_CRITICAL_MEM
        number in percent alert for MEM usage
        -N, --ntwlimit=WARNING_NET_RX,WARNING_NET_TX,CRITCAL_NET_RX,CRITCAL_NET_TX
        bandwidth (RX -> DL,TX -> UL) in kBps for docker selected
        -s, --status
        check if docker is alive

[ec2-user@ip-172-31-44-152 ~]$ sudo bash check_docker.sh --name voo4-collecte --status --cpulimitperc 00,90
voo4-collecte OK , running

Reading the code, the equal sign is not useful, but documentation still give it
        -c, --cpulimitperc**=**PERC_WARNING_CPU,PERC_CRITCAL_CPU
        -m, --memlimitperc**=**PERC_WARNING_MEM,PERC_CRITICAL_MEM

**Comment by sysC0D** [comment]
Hi,

Sorry, my help description had error.
I just updated. 

sysC0D
