### ISSUE TITLE
For which docker version ? 

### ISSUE THREAD

**Issue by senseicoder** [sysC0D/nagios-plugin#2]
Hi, 

--format is not an existing parameter for docker stats (I use a Docker 1.10 on customer server), and without the pretty print format even shortid grep does not catch anything. 
So, which is the lower version your script is compatible with ? 

Regards
Cédric

**Comment by sysC0D** [comment]
Hi,

I just updated check_docker.sh for verify minimal docker version (now v1.10) and use different treatment for version 1.10.0 to 1.12.X

Best regards
sysC0D

**Comment by senseicoder** [comment]
Thanks, I check asap.

Best regards
Cédric
